[package]
name = "heli-otr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.0-rc.3"
rkyv = "0.7"
zstd = "0.13"
regex = "1.10"
unicode-blocks = "0.1.8"
shingles = "0.1"
ordered-float = "4.2"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_debug"]}
env_logger = "0.10"
strum = { version = "0.25", features = ["derive"] }
fnv = "1.0"
wyhash2 = "0.2.1"

[dev-dependencies]
test-log = "0.2.15"
