[package]
name = "heli_otr"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "heli_otr"
# use lib to be able to compile library from other rust crates
# use cdylib to enable maturin linkage
crate-type = ["lib", "cdylib"]

[dependencies]
bitcode = "0.6"
regex = "1.10"
unicode-blocks = "0.1.8"
shingles = "0.1"
ordered-float = "4.2"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_debug"]}
env_logger = "0.10"
strum = { version = "0.25", features = ["derive"] }
wyhash2 = "0.2.1"
pyo3 = "0.20.0"

[dev-dependencies]
test-log = "0.2.15"
