[package]
name = "heli-otr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.0-rc.3"
zstd = "0.13"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"]}
env_logger = "0.10"
