[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "heli_otr"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[project.scripts]
heli = "heli_otr:cli_run"
heli-convert = "heli_otr:cli_convert"
heli-download = "heli_otr:cli_download"

[tool.maturin]
features = ["pyo3/extension-module"]
